# Generated by Django 5.2.12 on 2026-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural'), ('OTHERS', 'Others')], max_length=20)),
                ('sub_type', models.CharField(blank=True, choices=[('HOUSE', 'House / Villa'), ('APARTMENT', 'Apartment / Flat'), ('RESIDENTIAL_PLOT', 'Residential Plot'), ('TOWNHOUSE', 'Townhouse'), ('VACATION_HOME', 'Vacation Home'), ('COOP_HOUSING', 'Cooperative Housing Society'), ('OFFICE', 'Office Space'), ('SHOP', 'Shop / Retail Unit'), ('MALL', 'Shopping Mall'), ('MARKET', 'Sabzi Mandi / Market'), ('HOSPITALITY', 'Hotel / Motel / Resort'), ('RESTAURANT', 'Restaurant / Eatery'), ('RECREATION', 'Cinema / Theatre / Park'), ('PARKING', 'Parking Facility'), ('FACTORY', 'Factory / Manufacturing Unit'), ('WAREHOUSE', 'Warehouse / Storage'), ('INDUSTRIAL_PARK', 'Industrial Park / Zone'), ('POWER_PLANT', 'Power Plant'), ('FARM', 'Cultivation Farm / Farmland'), ('ORCHARD', 'Orchard'), ('RANCH', 'Ranch / Livestock Farm'), ('FISH_FARM', 'Fish Farm'), ('RAW_LAND', 'Raw / Unserviced Plot'), ('SERVICED_PLOT', 'Serviced Plot'), ('MIXED_HIGHRISE', 'Mixed-Use High-Rise'), ('RETAIL_RESIDENTIAL', 'Retail / Residential'), ('SCHOOL', 'School / Educational Institution'), ('RELIGIOUS', 'Mosque / Religious Center'), ('HOSPITAL', 'Hospital / Healthcare Facility'), ('GOVT', 'Government / Administrative Building'), ('TOURISM', 'Tourism Infrastructure')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active / Ongoing'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20)),
                ('start_date', models.DateField()),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_unit', models.CharField(default='Kanal', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
