# Generated by Django 5.2.12 on 2026-04-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
    ]
