# Generated by Django 5.2.12 on 2026-04-12 09:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(help_text='Format: 35202-1234567-1', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in format: 35202-1234567-1', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('phone', models.CharField(help_text='Format: 03001234567', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be Pakistani format: 03001234567 or +923001234567', regex='^(\\+92|0)[0-9]{10}$')])),
                ('address', models.TextField(help_text='Full mailing address')),
                ('city', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(blank=True, help_text='Father / Husband name — used in legal documents', max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='customers/photos/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
