# Generated by Django 5.2.12 on 2026-04-12 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cnic',
            field=models.CharField(help_text='Format: 35202-1234567-1', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in format: 35202-1234567-1', regex='^\\d{5}-\\d{7}-\\d{1}$')]),
        ),
    ]
