# Generated by Django 5.2.12 on 2026-04-12 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cnic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='guardian_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone must be Pakistani format: 03001234567 or +923001234567', regex='^(\\+92|0)[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cnic',
            field=models.CharField(db_index=True, help_text='Format: 35202-1234567-1', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in format: 35202-1234567-1', regex='^\\d{5}-\\d{7}-\\d{1}$')]),
        ),
    ]
