# Generated by Django 5.2.12 on 2026-04-12 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_guardian_name_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__username'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='agreement_copy',
            field=models.FileField(blank=True, help_text='Signed agreement — PDF or image', null=True, upload_to='customers/agreements/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cnic_back',
            field=models.ImageField(blank=True, help_text='Back side of CNIC', null=True, upload_to='customers/cnic/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cnic_front',
            field=models.ImageField(blank=True, help_text='Front side of CNIC', null=True, upload_to='customers/cnic/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='Father / Husband name — used in legal documents', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_alt',
            field=models.CharField(blank=True, help_text='Optional alternate number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone must be Pakistani format: 03001234567 or +923001234567', regex='^(\\+92|0)[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Passport size photo', null=True, upload_to='customers/photos/'),
        ),
    ]
